language: python
python:
  - "3.5"
notifications:
  email: false
before_install:
  - pip install coveralls
install:
  - python setup.py install
  - pip install coverage
  - pip install pytest
  - pip install pytest-qt
  - pip install pytest-xvfb
  - pip install pytest-faulthandler
  - pip install pyqt5
script:
  - py.test -s
  - coverage run test_mpad.py
after_success:
  - coveralls