language: python
python:
  - "3.5.2"
sudo: required
dist: trusty
notifications:
  email: false
sudo: required
before_install:
  - pip install coveralls
install:
  - python setup.py install
  - pip install coverage
  - pip install pytest
  - pip install pytest-qt
  - pip install pytest-faulthandler
  - sudo apt-get update
  - sudo apt-get install xvfb python3-pyqt5
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - py.test -s -v
  - coverage run test_mpad.py
after_success:
  - coveralls