language: python
python:
  - "3.5"
notifications:
  email: false
before_install:
  - pip install coveralls
install:
  - python setup.py install
  - pip install coverage
  - pip install pytest
script:
  - py.test tests.py
  - coverage run tests.py
after_success:
  - coveralls